
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."JSON_VIEW" ("FIRST_NAME", "LAST_NAME") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT  JSON_VALUE(json_data, '$.FIRST_NAME') AS "FIRST_NAME", JSON_VALUE(json_data, '$.LAST_NAME') AS "LAST_NAME" FROM JSON_DATA_TEST;

