
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."NL2SQL_V_PROFILE_MODEL_TIMES_GROUPED" ("MODEL", "AVG_TIME_SELECTAI", "AVG_TIME_AGENT_SELECTAI") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
  CASE
    WHEN INSTR(PROFILE, 'UNIVERSITY_SELECTAI_') = 1 THEN SUBSTR(PROFILE, 21)
    WHEN INSTR(PROFILE, 'UNIVERSITY_AGENT_SELECTAI_') = 1 THEN SUBSTR(PROFILE, 27)
    ELSE PROFILE
  END AS MODEL,
  ROUND(AVG(CASE WHEN INSTR(PROFILE, 'UNIVERSITY_SELECTAI_') = 1 THEN avg_one_question_sec END), 2) AS AVG_TIME_SELECTAI,
  ROUND(AVG(CASE WHEN INSTR(PROFILE, 'UNIVERSITY_AGENT_SELECTAI_') = 1 THEN avg_one_question_sec END), 2) AS AVG_TIME_AGENT_SELECTAI
FROM NL2SQL_V_PROFILE_AVG_SIMPLE
GROUP BY CASE
    WHEN INSTR(PROFILE, 'UNIVERSITY_SELECTAI_') = 1 THEN SUBSTR(PROFILE, 21)
    WHEN INSTR(PROFILE, 'UNIVERSITY_AGENT_SELECTAI_') = 1 THEN SUBSTR(PROFILE, 27)
    ELSE PROFILE
  END
ORDER BY MIN(avg_one_question_sec) ASC;

