
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."NL2SQL_V_PROMPT_RESPONSES" ("PROFILE_NAME", "PROMPT_IDENTIFIER", "PROMPT_TEXT", "RESPONSE_TEXT", "ROUND_TRIP_SEC", "IS_VALID") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
  p.profile AS "PROFILE_NAME",
  p.id AS "PROMPT_IDENTIFIER",
  p.prompt AS "PROMPT_TEXT",
  p.response AS "RESPONSE_TEXT",
  ROUND(b.round_trip_sec,2) AS "ROUND_TRIP_SEC",
  r.IS_VALID AS "IS_VALID"
FROM NL2SQL_PROMPTS p
INNER JOIN NL2SQL_V_BATCH_ROUNDTRIP b
  ON p.id = b.prompt_id
LEFT JOIN NL2SQL_RESPONSE_RATINGS r
    ON p.id = r.PROMPT_ID
ORDER BY p.asked_on, p.id;

