
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."NL2SQL_V_PROFILE_MODEL_TIMES" ("MODEL", "PROFILE_NAME", "AVERAGE_TIME_PER_QUESTION", "NUMBER_OF_QUESTIONS_ASKED", "INVALID_RESPONSE_COUNT") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
  CASE
    WHEN INSTR(ps.PROFILE, 'UNIVERSITY_SELECTAI_') = 1 THEN SUBSTR(ps.PROFILE, 21)
    WHEN INSTR(ps.PROFILE, 'UNIVERSITY_AGENT_SELECTAI_') = 1 THEN SUBSTR(ps.PROFILE, 27)
    ELSE ps.PROFILE
  END AS MODEL,
  ps.PROFILE AS PROFILE_NAME,
  ROUND(ps.avg_one_question_sec, 2) AS AVERAGE_TIME_PER_QUESTION,
  ps.questions_asked AS NUMBER_OF_QUESTIONS_ASKED,
  COALESCE(r.invalid_response_count, 0) AS INVALID_RESPONSE_COUNT
FROM NL2SQL_V_PROFILE_AVG_SIMPLE ps
LEFT JOIN (
  SELECT
    p.PROFILE,
    SUM(CASE WHEN nr.IS_VALID = 0 THEN 1 ELSE 0 END) AS invalid_response_count,
    ROUND(AVG(nr.RATING), 2) AS average_rating
  FROM NL2SQL_PROMPTS p
  LEFT JOIN NL2SQL_RESPONSE_RATINGS nr
    ON nr.PROMPT_ID = p.ID
  WHERE p.PROFILE LIKE 'UNIVERSITY_%'
  GROUP BY p.PROFILE
) r
  ON r.PROFILE = ps.PROFILE
ORDER BY MODEL, AVERAGE_TIME_PER_QUESTION ASC;

