
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."V_CUSTOMERORDERS" ("CUSTOMER_ID", "CUST_FIRST_NAME", "CUST_LAST_NAME", "STREET_ADDRESS", "POSTAL_CODE", "CITY", "STATE_PROVINCE", "COUNTRY_ID", "PHONE_NUMBER", "NLS_LANGUAGE", "NLS_TERRITORY", "CREDIT_LIMIT", "CUST_EMAIL", "ACCOUNT_MGR_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS
  select "CUSTOMER_ID","CUST_FIRST_NAME","CUST_LAST_NAME","STREET_ADDRESS","POSTAL_CODE","CITY","STATE_PROVINCE","COUNTRY_ID","PHONE_NUMBER","NLS_LANGUAGE","NLS_TERRITORY","CREDIT_LIMIT","CUST_EMAIL","ACCOUNT_MGR_ID" from OEHR_CUSTOMERS;

