
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DEV_USER"."VW_IN_DOA" ("ID", "SUBJECT", "PRIORITY", "STATUS", "DUE_DATE", "NAME", "PRICE_VALUE", "EXPLANATION", "REC_VENDOR_NAME", "REC_SUPPLIER_ID", "REC_VENDOR_ADDRESS", "REC_FUTURE_USE", "AGENCY", "PS_BUS_UNIT", "PS_REQ_ID", "AGENCY_ANALYST", "CONTACT_PERSON", "CONTACT_PHONE", "CONTACT_EMAIL", "COVID_Y_N", "CONTRACT_TYPE", "PREVIOUS_APPROVED_PURCHASE", "IC_PROVISIONS_FOR_SPECIAL_PROCUREMENT", "PURCHASE_DESCRIPTION", "SCOPE_SUMMARY", "FEDERAL_REQ", "CITED_REQUIREMENTS") DEFAULT COLLATION "USING_NLS_COMP"  AS
  SELECT
    s.ID                       AS ID,
    s.SUBJECT                  AS SUBJECT,
    s.PRIORITY                 AS PRIORITY,
    s.STATUS                   AS STATUS,
    s.DUE_DATE                 AS DUE_DATE,
    v.NAME                     AS NAME,
    v.PRICE_VALUE              AS PRICE_VALUE,
    v.EXPLANATION              AS EXPLANATION,
    v.REC_VENDOR_NAME          AS REC_VENDOR_NAME,
    v.REC_SUPPLIER_ID          AS REC_SUPPLIER_ID,
    v.REC_VENDOR_ADDRESS       AS REC_VENDOR_ADDRESS,
    v.REC_FUTURE_USE           AS REC_FUTURE_USE,
    a.AGENCY                   AS AGENCY,
    a.PS_BUS_UNIT              AS PS_BUS_UNIT,
    a.PS_REQ_ID                AS PS_REQ_ID,
    a.AGENCY_ANALYST           AS AGENCY_ANALYST,
    a.CONTACT_PERSON           AS CONTACT_PERSON,
    a.CONTACT_PHONE            AS CONTACT_PHONE,
    a.CONTACT_EMAIL            AS CONTACT_EMAIL,
    a.COVID_Y_N                AS COVID_Y_N,
    a.CONTRACT_TYPE            AS CONTRACT_TYPE,
    a.PREVIOUS_APPROVED_PURCHASE AS PREVIOUS_APPROVED_PURCHASE,
    p.IC_PROVISIONS_FOR_SPECIAL_PROCUREMENT AS IC_PROVISIONS_FOR_SPECIAL_PROCUREMENT,
    p.PURCHASE_DESCRIPTION     AS PURCHASE_DESCRIPTION,
    p.SCOPE_SUMMARY            AS SCOPE_SUMMARY,
    p.FEDERAL_REQ              AS FEDERAL_REQ,
    p.CITED_REQUIREMENTS       AS CITED_REQUIREMENTS
FROM
    IN_DOA_AGENCY_INFO            a,
    IN_DOA_PURCHASE_DETAILS       p,
    IN_DOA_SPR                    s,
    IN_DOA_VENDOR_INFORMATION     v
WHERE
    s.ID = v.IN_DOA_SPR_ID
    AND s.ID = p.IN_DOA_SPR_ID
    AND s.ID = a.IN_DOA_SPR_ID;

