prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/app_247_push_notifications_credentials.sql
@@workspace/credentials/cloud_tenancy_apikey.sql
@@workspace/remote_servers/objectstorage_us_ashburn_1_oraclecloud_com_n_natdcshjumpstartprod.sql
@@workspace/remote_servers/identity_us_ashburn_1_oci_oraclecloud_com.sql
@@workspace/remote_servers/api_sunrise_sunset_org.sql
@@application/shared_components/data_profiles/test_json_source.sql
@@application/shared_components/data_profiles/list_tenancy_compartments.sql
@@application/shared_components/data_profiles/list_compartment_buckets.sql
@@application/shared_components/data_profiles/list_object_in_bucket.sql
@@application/shared_components/data_profiles/sunset_public_api.sql
@@application/shared_components/web_sources/list_tenancy_compartments.sql
@@application/shared_components/web_sources/list_compartment_buckets.sql
@@application/shared_components/web_sources/list_object_in_bucket.sql
@@application/shared_components/web_sources/sunset_public_api.sql
@@application/shared_components/json_source/test_json_source.sql
@@application/shared_components/workflow/task_definitions/test.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/lists/user_interface.sql
@@application/shared_components/navigation/lists/activity_reports.sql
@@application/shared_components/navigation/lists/access_control.sql
@@application/shared_components/navigation/lists/feedback.sql
@@application/shared_components/navigation/lists/user_settings.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/persona_female03_png.sql
@@application/shared_components/files/persona_female04_oracle_png.sql
@@application/shared_components/files/persona_male01_apex_png.sql
@@application/shared_components/files/persona_male03_png.sql
@@application/shared_components/files/persona_male04_apex_png.sql
@@application/shared_components/files/jquery_mask_js.sql
@@application/shared_components/files/jquery_mask_min_js.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/security/authorizations/reader_rights.sql
@@application/shared_components/security/authorizations/contribution_rights.sql
@@application/shared_components/security/app_access_control/administrator.sql
@@application/shared_components/security/app_access_control/contributor.sql
@@application/shared_components/security/app_access_control/reader.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/desktop_theme_styles.sql
@@application/shared_components/user_interface/lovs/eba_demo_ig_dept_dname.sql
@@application/shared_components/user_interface/lovs/eba_demo_ig_emp_ename.sql
@@application/shared_components/user_interface/lovs/email_username_format.sql
@@application/shared_components/user_interface/lovs/feedback_rating.sql
@@application/shared_components/user_interface/lovs/feedback_status.sql
@@application/shared_components/user_interface/lovs/list_compartment_buckets.sql
@@application/shared_components/user_interface/lovs/list_tenancy_compartments.sql
@@application/shared_components/user_interface/lovs/oehr_customers_cust_first_name.sql
@@application/shared_components/user_interface/lovs/oehr_departments_department_name.sql
@@application/shared_components/user_interface/lovs/oehr_employees_first_name.sql
@@application/shared_components/user_interface/lovs/oehr_jobs_job_title.sql
@@application/shared_components/user_interface/lovs/timeframe_4_weeks.sql
@@application/shared_components/user_interface/lovs/user_theme_preference.sql
@@application/shared_components/user_interface/lovs/view_as_report_chart.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/report/cards_alternative.sql
@@application/shared_components/user_interface/templates/report/copy_content_row_multiple_actions.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/copy_of_demo_purposes_only_custom_auth_scheme.sql
@@application/shared_components/plugins/template_component/theme_42_shaynedev_comments.sql
@@application/shared_components/plugins/dynamic_action/com_enhanceigwithtreegrid_plugin.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_09999.sql
@@application/pages/page_10000.sql
@@application/pages/page_10010.sql
@@application/pages/page_10020.sql
@@application/pages/page_10030.sql
@@application/pages/page_10031.sql
@@application/pages/page_10032.sql
@@application/pages/page_10033.sql
@@application/pages/page_10034.sql
@@application/pages/page_10035.sql
@@application/pages/page_10036.sql
@@application/pages/page_10040.sql
@@application/pages/page_10041.sql
@@application/pages/page_10042.sql
@@application/pages/page_10043.sql
@@application/pages/page_10044.sql
@@application/pages/page_10050.sql
@@application/pages/page_10051.sql
@@application/pages/page_10053.sql
@@application/pages/page_10054.sql
@@application/pages/page_10060.sql
@@application/pages/page_10061.sql
@@application/pages/page_20000.sql
@@application/pages/page_20010.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
